In this file, I'm planning to do some numpy exercises, so that, I can find and fill the gaps also. I have found a repo of bunch of numpy exercises, which, I'll try solving. If I'm unable to solve it, I'll add my version, plus the correct version.

#### 1. Import the numpy package under the name `np`

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10

In [6]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array?

In [7]:
a = np.zeros(10, dtype='int')
print(a.itemsize)

8


#### 5. Create a null vector of size 10 but the fifth value which is 1

In [11]:
a = np.zeros(10, dtype='int')
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 6. Create a vector with values ranging from 10 to 49

In [2]:
a = np.array(range(10, 50))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last)

In [3]:
a[0], a[a.size - 1] = a[a.size - 1], a[0]
a

array([49, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
b = np.random.rand((3, 3), 0, 9)

TypeError: 'tuple' object cannot be interpreted as an integer

This np.random.rand() is a method which will provide a np array with values between 0 and 1, so, only shape is the argument. For our usecase, np.random.randint(low, high, shape) will serve the most..

In [7]:
b = np.random.randint(0, 9, (3, 3))
b

array([[0, 7, 8],
       [7, 7, 8],
       [6, 0, 3]], dtype=int32)

Here, 9 is given as it is exclusive..

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [18]:
c = np.array([1,2,0,0,4,0])
arr1 = np.array(x!=0 for x in c)
arr1

array(<generator object <genexpr> at 0x0000027A3C852740>, dtype=object)

In [23]:
# Above method is wrong.

c = np.array([1,2,0,0,4,0])
arr1 = c != 0
tt = np.where(arr1)
print(tt)
print(type(tt))
c[tt]

(array([0, 1, 4]),)
<class 'tuple'>


array([1, 2, 4])

Here, where is a function which can be used to get the index values from the boolean mask created with the help of the provided numpy array

#### 10. Create a 3x3 identity matrix

In [26]:
np.identity(3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])