In this file, I'm planning to do some numpy exercises, so that, I can find and fill the gaps also. I have found a repo of bunch of numpy exercises, which, I'll try solving. If I'm unable to solve it, I'll add my version, plus the correct version.

#### 1. Import the numpy package under the name `np`

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10

In [6]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array?

In [7]:
a = np.zeros(10, dtype='int')
print(a.itemsize)

8


#### 5. Create a null vector of size 10 but the fifth value which is 1

In [11]:
a = np.zeros(10, dtype='int')
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 6. Create a vector with values ranging from 10 to 49

In [2]:
a = np.array(range(10, 50))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last)

In [3]:
a[0], a[a.size - 1] = a[a.size - 1], a[0]
a

array([49, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
b = np.random.rand((3, 3), 0, 9)

TypeError: 'tuple' object cannot be interpreted as an integer

This np.random.rand() is a method which will provide a np array with values between 0 and 1, so, only shape is the argument. For our usecase, np.random.randint(low, high, shape) will serve the most..

In [7]:
b = np.random.randint(0, 9, (3, 3))
b

array([[0, 7, 8],
       [7, 7, 8],
       [6, 0, 3]], dtype=int32)

Here, 9 is given as it is exclusive..

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [18]:
c = np.array([1,2,0,0,4,0])
arr1 = np.array(x!=0 for x in c)
arr1

array(<generator object <genexpr> at 0x0000027A3C852740>, dtype=object)

In [23]:
# Above method is wrong.

c = np.array([1,2,0,0,4,0])
arr1 = c != 0
tt = np.where(arr1)
print(tt)
print(type(tt))
c[tt]

(array([0, 1, 4]),)
<class 'tuple'>


array([1, 2, 4])

Here, where is a function which can be used to get the index values from the boolean mask created with the help of the provided numpy array

#### 10. Create a 3x3 identity matrix

In [26]:
np.identity(3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 11. Create a 3x3x3 array with random values

In [9]:
np.random.randint(0, 15, (3, 3, 3))

array([[[ 3,  1,  1],
        [ 7, 11,  5],
        [ 3, 11, 13]],

       [[ 7,  1, 13],
        [ 5, 12,  5],
        [ 0,  8,  3]],

       [[13,  7,  5],
        [ 8,  9, 11],
        [13,  0, 10]]], dtype=int32)

#### 12. Create a 10x10 array with random values and find the minimum and maximum values

In [10]:
arr = np.random.randint(0, 10, (10, 10))
print(arr)

print(np.max(arr))
print(np.min(arr))

[[8 8 5 8 3 9 1 3 9 9]
 [5 7 4 9 5 5 1 6 5 8]
 [1 8 5 0 2 9 2 9 3 1]
 [5 5 8 7 3 1 7 9 2 0]
 [5 1 6 4 8 7 2 9 8 9]
 [4 2 5 5 6 7 5 4 5 9]
 [8 6 3 1 8 1 7 8 7 5]
 [9 7 0 4 6 6 9 5 3 3]
 [2 9 5 3 3 4 6 3 3 0]
 [0 9 8 5 8 1 6 3 2 4]]
9
0


#### 13. Create a random vector of size 30 and find the mean value

In [13]:
arr1 = np.random.randint(1, 100, (30))
print(arr1)
print(np.mean(arr1))

[89 14  7 48 69 88 29 72 96 96  7 54 61 66 88 43 31 65 99 52 37 79 12 33
 28 66 57  9 82 64]
54.7


#### 14. Create a 2d array with 1 on the border and 0 inside

In [17]:
arr2 = np.full((5, 5), 1)
arr3 = np.full((3, 3), 0)
arr2[1:4, 1:4] = arr3
arr2

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 15. How to add a border (filled with 0's) around an existing array?

By the previous cell way, or by using np.pad, we can solve this question.

In [28]:
arr2 = np.full((5,5), 1)
np.pad(arr2, pad_width=1, mode='constant', constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [30]:
help(np.pad)

Help on _ArrayFunctionDispatcher in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.
    
    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
        for each axis.
        ``(before, after)`` or ``((before, after),)`` yields same before
        and after pad for each axis.
        ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
        for all axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.
    
        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum

It has 4 common modes - constant (pads the center array with a value in a width), edge (repeat the edge values), reflect (mirrors the inside values), wrap (considers the array as infinitely repeated in all the directions and set the next repeating number of the array)